### ISSUE TITLE
Not workin on Xcode Version 6.2 (6C131e)

### ISSUE THREAD

**Issue by arctouch-brunopinheiro** [yuhua-chen/MCLog#11]
The text box to put the regex is missing

**Comment by alexlee002** [comment]
https://github.com/alexlee002/MCLog

This's my fork and fixed this issue. But there is a bug that it seems some times would lose some log--some one had reported this issue before. But it is not be fixed yet.

Maybe you ca help me to test it and give me more information to fix it.  Thanks.

Alex

**Comment by yuhua-chen** [comment]
Thanks @alexlee002~ I gonna fix this issue soon. :smile:

**Comment by alexlee002** [comment]
The confusing issue is still being opened, so I didn't create new pull request after I added support for 6.2.

发自我的 iPhone
