### ISSUE TITLE
Not work on Xcode 6.3

### ISSUE THREAD

**Issue by e7fendy** [yuhua-chen/MCLog#14]

**Comment by alexlee002** [comment]
Okey, got it. I'll fix it today

发自我的 iPhone

**Comment by lemonkey** [comment]
Confirmed as well. Looking forward to fix :)

**Comment by lemonkey** [comment]
+1

**Comment by lemonkey** [comment]
:+1:

**Comment by n0quarter** [comment]
+1

**Comment by yuhua-chen** [comment]
Not update Xcode yet. :stuck_out_tongue:

**Comment by n0quarter** [comment]
@yuhua-chen, do you have an idea what could be wrong and how to fix it ?
May be I can do it.

**Comment by alexlee002** [comment]
wait for my update version(maybe some days later)

OR:

```
cd ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin/Contents
vim Info.plist
```
add "__ <pre><string>9F75337B-21B4-4ADC-B558-F9CADF7073A7</string></pre>__"
to array for key "__DVTPlugInCompatibilityUUIDs__"

**Comment by yuhua-chen** [comment]
Thanks! I put it into code first.

**Comment by e7fendy** [comment]
Thanks a lot.

**Comment by yuhua-chen** [comment]
:beers:

**Comment by alexlee002** [comment]
Hi guys,
I wrote a shell script to update all installed Xcode plugins to support the new-updated Xcode,  no need to wait for the plugin's update. here is the script:

https://gist.github.com/alexlee002/b87dbeac1f9fd896174b

**Comment by yuhua-chen** [comment]
Thanks! That's awesome! :tada:
