### ISSUE TITLE
Causes Unit Tests to report "Test Succeeded" upon failure...

### ISSUE THREAD

**Issue by perlguy99** [yuhua-chen/MCLog#16]
Found this trying to do a simple comparison to see if a latitude was 0...

I verified that this behavior goes away if I uninstall MCLog and re-appears if I install MCLog.

When I run the my test, I have 2 NSNumbers.  The latitude is a float, the other value I have tried both an int and a float with the same results.

In the logging area, it shows the result that is expected, failure, however the pop-up message and the tone that I hear both say that the "Test Succeeded"

Steps to Reproduce:
Here is the code:

- (void)test_validate_location_tracking_is_working_apple
{
    NSNumber *compareZero = [[NSNumber alloc] initWithFloat:0];
    NSNumber *latitude    = [[NSNumber alloc] initWithFloat:99.99];
    
    if ([latitude isEqualToNumber:compareZero]) {
        NSLog(@"[latitude isEqualToNumber:compareZero] TRUE 1");
    }
    else {
        NSLog(@"[latitude isEqualToNumber:compareZero] FALSE 1");
    }
    
    if (latitude == compareZero) {
        NSLog(@"latitude == compareZero TRUE 2");
    }
    else {
        NSLog(@"latitude == compareZero FALSE 2");
    }
    
    XCTAssertEqual([latitude floatValue], [compareZero floatValue]);
}

Expected Results:
Pop-up message should say Test Failed.

Actual Results:
Pop-up message says Test Succeeded

Version:
Xcode 6.3 (6D570)

**Comment by yuhua-chen** [comment]
Hmm.. sounds weird! Let me try to reproduce this issue.

**Comment by yuhua-chen** [comment]
I got correct results. This test failed normally no matter i enable or disable this plugin. Could you create a new project to test again? I hope we can reproduce this issue under clean environment to figure out.
