### ISSUE TITLE
not work on XCode Version 6.3.2 , OSX 10.10.3

### ISSUE THREAD

**Issue by xn4545945** [yuhua-chen/MCLog#19]
E969541F-E6F9-4D25-8158-72DC3545A6C6          Added this still not work

**Comment by alexlee002** [comment]
restart xcode?

**Comment by alexlee002** [comment]
https://gist.github.com/alexlee002/b87dbeac1f9fd896174b

**Comment by xn4545945** [comment]
Sorry, it is my mistake. it works normally after added E969541F-E6F9-4D25-8158-72DC3545A6C6
uninstall , reinstall.  
i Ignored this popup window. "Unexpected code bundle MCLog.xcpiugin". After choose "Load Bundle", it works. it is a new popup window in xcode6.3.2.

**Comment by benf1977** [comment]
Hmm, I'm seeing this too. I've tried reinstalling and restarting xcode.

**Comment by yuhua-chen** [comment]
I just updated the UUIDs and checked on Xcode 6.3.2. Don't forget to click "**Load Bundle**" when popup showing. It's new feature of this version of Xcode. 
![2015-05-28 11 30 35](https://cloud.githubusercontent.com/assets/2312017/7852639/6158343e-0533-11e5-9938-ba9382325fde.png)
If you clicked "Skip" before, you had to remove plugin while Xcode's opening and install it again.

**Comment by ricardobed** [comment]
@yuhua-chen Just verified it works on Xcode 6.3.2. Thanks a lot!

**Comment by yuhua-chen** [comment]
:beers:
