### ISSUE TITLE
Last NSLog always missing

### ISSUE THREAD

**Issue by hbmtw** [yuhua-chen/MCLog#20]
For some reason, the plugin always "filters away" the last NSLog. For example:
NSLog(@"Whats up");
NSLog(@"Whats up 2");
NSLog(@"Whats up 3");

gives:
2015-05-26 16:32:37.760 Dilemma[992:66937] Whats up
2015-05-26 16:32:37.760 Dilemma[992:66937] Whats up 2

Missing the last NSLog.

Crazy! But thanks for the plugin nonetheless, just messed with my head.

**Comment by yuhua-chen** [comment]
hmm it's same issue with #6 . Still can't find out. Can you tell me more details? How to reproduce this bug?

**Comment by hbmtw** [comment]
Well, 
Install the plugin
And just in any viewDidLoad, write the above three NSLogs :)

**Comment by yuhua-chen** [comment]
Hi~ I use GCD instead of NSTimer to take care of parse output. Try latest version(d0029cc1366be0fb9d95e81b7b2ec2f3f42caaa0). Check if works or not.

**Comment by yuhua-chen** [comment]
Duplicated with #6. Let's discuss there.
