### ISSUE TITLE
Need Xcode 6.4 support

### ISSUE THREAD

**Issue by ricardobed** [yuhua-chen/MCLog#23]
Hi,

It was working fine on Xcode 6.3.2 but with the release of 6.4 it stopped working. Can you please add the UDID so it can work again? Thanks!

**Comment by alexlee002** [comment]
Run this shell:

https://gist.github.com/alexlee002/b87dbeac1f9fd896174b

**Comment by mverderese** [comment]
Just submitted a pull request for this:  https://github.com/yuhua-chen/MCLog/pull/24
In the meantime, you can use my fork for Xcode 6.4 support: https://github.com/mverderese/MCLog
