### ISSUE TITLE
Additional functionality for console?

### ISSUE THREAD

**Issue by gerchicov-bp** [yuhua-chen/MCLog#26]
If you filter the messages then maybe could you add a support of macro? I mean at least something easy, for example:
#define A @"fdgd"
#define someMacro(x) NSLog(@"%@", x)

The default xcode behaviour - all the macro code is not supported

**Comment by yuhua-chen** [comment]
I think if this plugin supports some macro that may cause some side effect of code base. And we don't have any specification of which macro we need. Appreciated your feedbacks. Thanks :smile:
