### ISSUE TITLE
Xcode source editor buggy opening Swift header or playground

### ISSUE THREAD

**Issue by lucianoks** [yuhua-chen/MCLog#35]
So, my Xcode was [crashing with MCLog installed] (https://github.com/yuhua-chen/MCLog/issues/30)  but [this solution](https://github.com/yuhua-chen/MCLog/issues/32#issuecomment-146582411) did make it work again (don't forget to [xcplugin_update](https://gist.github.com/alexlee002/b87dbeac1f9fd896174b) for new Xcode versions). =)

But this super-mega-alien-weird thing began to happen when I open saved playgrounds or Cmd-click on Obj-C classes that lead to Swiftyfied headers:

![screen shot 2](https://cloud.githubusercontent.com/assets/679503/11063216/38438f9e-879c-11e5-836f-149206033a56.png)

![screen shot 3](https://cloud.githubusercontent.com/assets/679503/11063225/3d9a0f68-879c-11e5-8d2d-1d3fd9d619c2.png)

Note how lines is kinda mixed altogheter. When I try to edit something within this mess, I get a crash with this [log](https://gist.github.com/lucianoks/557e8cbb997cd9e99af2).
I've already verified that MCLog is the only plugin installed when this occurs.
I can't use MCLog 'cause I need my editor working =(

**Comment by yuhua-chen** [comment]
Try out the latest version. It works now.
![playground](https://cloud.githubusercontent.com/assets/2312017/11204502/8552e142-8d3a-11e5-915b-8050ba91c8b2.png)

**Comment by lucianoks** [comment]
@yuhua-chen Working smoothly, thanks a lot! =)
