### ISSUE TITLE
Can not editor with japanese string

### ISSUE THREAD

**Issue by datnm** [yuhua-chen/MCLog#37]
@yuhua-chen the last MCLog source is not crash,
However, i can not editor japanese with xcode,
Please help me for this!
thank you!

i am running OSX El Capitan with xcode 7.1.

**Comment by yuhua-chen** [comment]
Hey~ Check out the latest version. It should work.
![playground](https://cloud.githubusercontent.com/assets/2312017/11204476/3c3f35dc-8d3a-11e5-92fa-029ab103847c.png)

**Comment by datnm** [comment]
@yuhua-chen 
thank you for lastest version of MCLog,
I checked out and check,
Now, it is very good,

**Comment by yuhua-chen** [comment]
:beers:
