### ISSUE TITLE
Can not display simplified Chinese in IDE window

### ISSUE THREAD

**Issue by OpenFibers** [yuhua-chen/MCLog#38]
Dear yuhua:

After install the newest version of MCLog, all simplified Chinese chars display as "", and new simplified Chinese chars cannot be inputted.
This is the localisation resource text file of my project. Before install MCLog:  
<img width="285" alt="screen shot 2015-11-16 at 5 56 15 pm" src="https://cloud.githubusercontent.com/assets/648499/11179038/9db94c12-8c8b-11e5-944e-79c2e526eeb1.png">

After install MCLog:  
<img width="259" alt="screen shot 2015-11-16 at 5 56 09 pm" src="https://cloud.githubusercontent.com/assets/648499/11179021/791b4b26-8c8b-11e5-8602-9a52d199486c.png">

请救救沦陷区的同胞 ：（

**Comment by yuhua-chen** [comment]
Sorry! I think the root cause is taking `fixAttributeRange:` way. Working on it. Duplicated with #37.
還在努力中 :joy:

**Comment by OpenFibers** [comment]
感谢回复，祝好运：D

**Comment by yuhua-chen** [comment]
@OpenFibers 已經修正，請下載最新版本。

**Comment by OpenFibers** [comment]
已安装，插件可以正常工作了，感谢🌚
