### ISSUE TITLE
Filtering truncates log

### ISSUE THREAD

**Issue by revolter** [yuhua-chen/MCLog#43]
Sometimes, when I filter by a word and `:` like `BUG:`, the log gets truncated. Could you point me to the exact place where the search happens to try and solve it?

**Comment by yuhua-chen** [comment]
hmm... guess like you may break the regex pattern?

**Comment by revolter** [comment]
I love and know regex, so that's not the case.

**Comment by yuhua-chen** [comment]
Let's move to thread #46.
