### ISSUE TITLE
Filter doesn't respect newlines

### ISSUE THREAD

**Issue by DanielAsher** [yuhua-chen/MCLog#44]
Hi,

thanks for a great plugin!

I use XCodeColors and KZLinkedConsole. When filtering with MCLog it looks like newlines are removed and becomes difficult to read.

Could you verify this?

thanks.

**Comment by yuhua-chen** [comment]
I tracked the KZLinkedConsole code. Not verifying in Xocde, but i can tell from the [code](https://github.com/krzysztofzablocki/KZLinkedConsole/blob/master/KZLinkedConsole/KZLinkedConsole.swift) that we did swizzle the same method. I copied part of the code:
```
static func swizzleMethods() {
        guard let storageClass = NSClassFromString("NSTextStorage") as? NSObject.Type,
            let textViewClass = NSClassFromString("NSTextView") as? NSObject.Type else {
                return
        }
        
        do {
            try storageClass.jr_swizzleMethod("fixAttributesInRange:", withMethod: "kz_fixAttributesInRange:")
            try textViewClass.jr_swizzleMethod("mouseDown:", withMethod: "kz_mouseDown:")
        }
        catch {
            Swift.print("Swizzling failed")
        }
    }
```
For now, these two plugins may work together. I'm thinking the solution or maybe have discuss with contributor of KZLinkedConsole.

**Comment by DanielAsher** [comment]
many thanks for your quick response :)

**Comment by DanielAsher** [comment]
Currently MCLog incompatible with KZLinkedConsole.
