### ISSUE TITLE
Only load if current application is Xcode 

### ISSUE THREAD

**Issue by puttin** [yuhua-chen/MCLog#45]
open opendiff(FileMerge) should not load MCLog

* [Xcode-Plugin-Template/NSObject_Extension.m](https://github.com/kattrali/Xcode-Plugin-Template/blob/9e3563dd988eaf5c63d97b362c0ecc40a749055d/Project%20Templates/Application%20Plug-in/Xcode%20Plugin.xctemplate/NSObject_Extension.m#L15)
* https://github.com/alcatraz/Alcatraz/issues/50
* [Alcatraz/Alcatraz.m](https://github.com/alcatraz/Alcatraz/blob/86b3f9bc4f6c02f929886583c0bebfd5a3053aa5/Alcatraz/Alcatraz.m#L33)

**Comment by alexlee002** [comment]
hmmm..... Can you please give me moe information? I'm not sure I catch your key point.

**Comment by puttin** [comment]
```
$ git difftool -t opendiff
```

see the log you will find 
```
+[MCLog load], env: (null)
[MCLog] +[MCLog pluginDidLoad:](Line:43) +[MCLog pluginDidLoad:], NSBundle </Users/****/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin> (loaded)
```

which should be ignored

see also 
https://github.com/omz/Dash-Plugin-for-Xcode/issues/51
https://github.com/shpakovski/Xprop/issues/11
