### ISSUE TITLE
Xcode 7.3 not loading this plugin

### ISSUE THREAD

**Issue by willard1218** [yuhua-chen/MCLog#48]
I'm download Xcode 7.3 and installed MCLog,
but Xcode not load MCLog when Xcode restart.

**Comment by michalzelinka** [comment]
Hi,

something has probably slightly changed in the Window hierarchy. I've managed to quick-patch it by copy-pasting some code from `PluginConsole` plugin, here's the diff.

[init-fix.txt](https://github.com/yuhua-chen/MCLog/files/186116/init-fix.txt)

**Comment by haojianzong** [comment]
Doesn't work after following @michalzelinka's quick patch advice.

**Comment by michalzelinka** [comment]
@haojianzong Did the patch applied correctly? It had my local file paths so the patch application could fail. Secondly, have you added Xcode 7.3 UUID to plugin's property list as well before building? Here's a fixed patch with both modifications you can apply directly on the cloned repository. Build, restart Xcode & enjoy.

[patch.diff.txt](https://github.com/yuhua-chen/MCLog/files/191680/patch.diff.txt)

**Comment by Naituw** [comment]
@michalzelinka Thanks Michal, MCLog works again after patch your diff~
Here is the repo applied the patch: https://github.com/Naituw/MCLog
