### ISSUE TITLE
不得不说，MCLog会导致我解析Json时输出丢失字段的问题。

### ISSUE THREAD

**Issue by jinxiansen** [yuhua-chen/MCLog#52]
如题，更确切的说，在控制台输出Json的时候因此会导致缺少json字段或标点符号等，从而不便使用EJsonFormat等插件，因为格式不对啊大兄弟。

**Comment by yuhua-chen** [comment]
了解...的確會有這樣的問題，主要是因為要去渲染文字顏色，不得不去把文字分段解析，導致有時候會有些訊息output不出來，目前還找不到什麼bug的主因

**Comment by jinxiansen** [comment]
oh,thinks !
