### ISSUE TITLE
Doesn't show latest log in Xcode 6

### ISSUE THREAD

**Issue by denbec** [yuhua-chen/MCLog#9]
It will only show the second oldest log in the console. So the console is always one log behind and you can't use it anymore.
Also in the newest beta as in the stable 6.1.

**Comment by alexlee002** [comment]
Ok, I'll check and fix it. Please wait for my pull request later

发自我的 iPhone

**Comment by alexlee002** [comment]
Hi, you can download the latest version from https://github.com/alexlee002/MCLog
But there still has this bug if you use NSLog directly.

What is confused me is that if you use the Macros（ALLogV etc.） I mentions in README.md to enable colorful log output,  then everything is OK.

**Comment by yuhua-chen** [comment]
duplicated with #6

**Comment by yuhua-chen** [comment]
It supports the newest Xcode right now and is duplicated. Let's move our conversation to #6.
